export { default as Archive } from 'lucide-svelte/icons/archive';
export { default as File } from 'lucide-svelte/icons/file';
export { default as Folder } from 'lucide-svelte/icons/folder';
export { default as Calendar } from 'lucide-svelte/icons/calendar';

export { default as AtSign } from 'lucide-svelte/icons/at-sign';
export { default as SunMoon } from 'lucide-svelte/icons/sun-moon';
export { default as MessageSquareDot } from 'lucide-svelte/icons/message-square-dot';
export { default as MonitorCheck } from 'lucide-svelte/icons/monitor-check';

export { default as School } from 'lucide-svelte/icons/school';
export { default as Coins } from 'lucide-svelte/icons/coins';
export { default as Users } from 'lucide-svelte/icons/users-round';
export { default as Dashboard } from 'lucide-svelte/icons/layout-dashboard';
export { default as ClipboardList } from 'lucide-svelte/icons/clipboard-list';
export { default as Buildings } from 'lucide-svelte/icons/building-2';

export { default as Fingerprint } from 'lucide-svelte/icons/fingerprint';
export { default as Cross } from 'lucide-svelte/icons/x';
export { default as Bell } from 'lucide-svelte/icons/bell';
export { default as PanelLeft } from 'lucide-svelte/icons/panel-left';

export { default as ArrowUpRight } from 'lucide-svelte/icons/move-up-right';
export { default as ArrowLeft } from 'lucide-svelte/icons/move-left';

export { default as CalendarDays } from 'lucide-svelte/icons/calendar-days';
export { default as Check } from 'lucide-svelte/icons/check';
export { default as RefreshCw } from 'lucide-svelte/icons/refresh-cw';
export { default as ChevronsUpDown } from 'lucide-svelte/icons/chevrons-up-down';
export { default as MixerHorizontal } from 'lucide-svelte/icons/sliders-horizontal';

export { default as Ellipsis } from 'lucide-svelte/icons/ellipsis';
export { default as PlusCircled } from 'lucide-svelte/icons/circle-plus';
export { default as Logout } from 'lucide-svelte/icons/log-out';
export { default as DotsVertical } from 'lucide-svelte/icons/ellipsis-vertical';
export { default as ChevronLeft } from 'lucide-svelte/icons/chevron-left';
export { default as ChevronRight } from 'lucide-svelte/icons/chevron-right';
export { default as ChevronsLeft } from 'lucide-svelte/icons/chevrons-left';
export { default as ChevronsRight } from 'lucide-svelte/icons/chevrons-right';
export { default as Mail } from 'lucide-svelte/icons/mail';
export { default as Phone } from 'lucide-svelte/icons/phone';
export { default as UserRoundPlus } from 'lucide-svelte/icons/user-round-plus';
export { default as UserRoundCheck } from 'lucide-svelte/icons/user-round-check';
export { default as UserRoundX } from 'lucide-svelte/icons/user-round-x';
export { default as UserRoundPen } from 'lucide-svelte/icons/user-round-pen';
export { default as CalendarMinus2 } from 'lucide-svelte/icons/calendar-minus-2';
export { default as Copy } from 'lucide-svelte/icons/copy';
export { default as Gears } from 'lucide-svelte/icons/settings';
export { default as Key } from 'lucide-svelte/icons/key';
export { default as ReceiptText } from 'lucide-svelte/icons/receipt-text';
export { default as Handshake } from 'lucide-svelte/icons/handshake';
export { default as User } from 'lucide-svelte/icons/user';
export { default as Briefcase } from 'lucide-svelte/icons/briefcase';
export { default as Building } from 'lucide-svelte/icons/building';
export { default as BanknoteIcon } from 'lucide-svelte/icons/banknote';

export { default as PhilippinePeso } from 'lucide-svelte/icons/philippine-peso';
export { default as Expand } from 'lucide-svelte/icons/expand';
export { default as ClockIcon } from 'lucide-svelte/icons/clock';
export { default as Laptop } from 'lucide-svelte/icons/laptop';
export { default as Moon } from 'lucide-svelte/icons/moon';
export { default as Sun } from 'lucide-svelte/icons/sun';
export { default as Search } from 'lucide-svelte/icons/search';
export { default as CircleAlert } from 'lucide-svelte/icons/circle-alert';
export { default as ShieldAlert } from 'lucide-svelte/icons/shield-alert';
export { default as Info } from 'lucide-svelte/icons/info';
export { default as CircleX } from 'lucide-svelte/icons/circle-x';
export { default as Send } from 'lucide-svelte/icons/send';
export { default as Smartphone } from 'lucide-svelte/icons/smartphone';
export { default as MonitorSmartphone } from 'lucide-svelte/icons/monitor-smartphone';
export { default as MonitorX } from 'lucide-svelte/icons/monitor-x';
export { default as UserX } from 'lucide-svelte/icons/user-x';
export { default as UserCheck } from 'lucide-svelte/icons/user-check';
export { default as CaseUpper } from 'lucide-svelte/icons/case-upper';
export { default as CaseSensitive } from 'lucide-svelte/icons/case-sensitive';
export { default as ChartCandlestick } from 'lucide-svelte/icons/chart-candlestick';
export { default as Pencil } from 'lucide-svelte/icons/pencil';
export { default as View } from 'lucide-svelte/icons/view';
export { default as ShieldOff } from 'lucide-svelte/icons/shield-off';

export { default as Save } from 'lucide-svelte/icons/save';
export { default as Ban } from 'lucide-svelte/icons/ban';
export { default as CirclePlus } from 'lucide-svelte/icons/circle-plus';
export { default as TrendingUp } from 'lucide-svelte/icons/trending-up';
export { default as ChartArea } from 'lucide-svelte/icons/chart-area';
export { default as ChartBar } from 'lucide-svelte/icons/chart-bar';
export { default as TrendingUpDown } from 'lucide-svelte/icons/trending-up-down';
export { default as ChevronDown } from 'lucide-svelte/icons/chevron-down';
export { default as ChevronUp } from 'lucide-svelte/icons/chevron-up';
export { default as Slash } from 'lucide-svelte/icons/slash';
export { default as Lock } from 'lucide-svelte/icons/lock';
export { default as Package } from 'lucide-svelte/icons/package';
export { default as BookUser } from 'lucide-svelte/icons/book-user';
export { default as ScrollText } from 'lucide-svelte/icons/scroll-text';
export { default as FileDown } from 'lucide-svelte/icons/file-down';
export { default as ArrowDownToLine } from 'lucide-svelte/icons/arrow-down-to-line';
export { default as CalendarX } from 'lucide-svelte/icons/calendar-x';

export { default as CircleHelp } from 'lucide-svelte/icons/circle-help';
export { default as Timer } from 'lucide-svelte/icons/timer';
export { default as Circle } from 'lucide-svelte/icons/circle';
export { default as CircleCheck } from 'lucide-svelte/icons/circle-check';
export { default as ArrowUp } from 'lucide-svelte/icons/arrow-up';
export { default as ArrowDown } from 'lucide-svelte/icons/arrow-down';
export { default as ArrowRight } from 'lucide-svelte/icons/arrow-right';
export { default as BriefcaseConveyorBelt } from 'lucide-svelte/icons/briefcase-conveyor-belt';
export { default as CreditCard } from 'lucide-svelte/icons/credit-card';
export { default as BadgeCheck } from 'lucide-svelte/icons/badge-check';
export { default as CalendarClock } from 'lucide-svelte/icons/calendar-clock';
export { default as ShieldCheck } from 'lucide-svelte/icons/shield-check';
export { default as Landmark } from 'lucide-svelte/icons/landmark';
export { default as Eye } from 'lucide-svelte/icons/eye';
export { default as EyeOff } from 'lucide-svelte/icons/eye-off';
export { default as TriangleAlert } from 'lucide-svelte/icons/triangle-alert';
export { default as Trash2 } from 'lucide-svelte/icons/trash-2'
export { default as Layers } from 'lucide-svelte/icons/layers';
export { default as ListFilter } from 'lucide-svelte/icons/list-filter';
export { default as LoaderCircle } from 'lucide-svelte/icons/loader-circle';
export { default as Settings2 } from 'lucide-svelte/icons/settings-2';
export { default as X } from 'lucide-svelte/icons/x';

// export { default as home_image } from './home.png';
// export { default as mail_image } from './email.png';
// export { default as phone_image } from './phone.png';
// export { default as www_image } from './www.png';
